### ISSUE TITLE
Enable_io Displaying HTML Entities

### ISSUE THREAD

**Issue by celtic-coder** [ThomasMertes/Seed7Home#1]
[comment]: # (https://github.com/ThomasMertes/Seed7Home/issues//1)

Hi Thomas (@ThomasMertes),

The Libraries page, [Enable_io](https://thomasmertes.github.io/Seed7Home/libraries/enable_io.htm), is displaying the HTML entities rather than the correct value for _"<&"_.

For example, here is the first of the two occurrences:

![HTML-Entity](https://github.com/ThomasMertes/Seed7Home/assets/11787866/86a689cd-5ca6-4a83-a846-c5e452fc515f)

The text reads "``and the operators lpad, rpad and &lt;&amp;``." The next occurrence is similar under the **enable_io** heading at the bottom of the page. 

Kind Regards,
Liam

**Comment by ThomasMertes** [comment]
Thank you very much for your feedback.

I have improved the script that generates the Seed7 Homepage. With the improvement the replacement of `<` and `&` with the HTML entities `&lt;` respectively `&amp;` is done when the wiki links are processed.

Now the descriptions of [enable_output](https://thomasmertes.github.io/Seed7Home/libraries/enable_io.htm#enable_output(in_type)) and [enable_io](https://thomasmertes.github.io/Seed7Home/libraries/enable_io.htm#enable_io(in_type)) both link to [<&](https://thomasmertes.github.io/Seed7Home/libraries/enable_io.htm#(in_string)%3C&(in_aType)) instead of [&amp;lt;&amp;amp;](https://thomasmertes.github.io/Seed7Home/libraries/enable_io.htm#(in_string)%3C&(in_aType)).

**Comment by celtic-coder** [comment]
Thanks, Thomas! (@ThomasMertes) 👍
